# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
        # Leave demo-files unaltered after download from BL website.
        exclude: "demo-files/.+xml"
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-xml
    -   id: check-added-large-files
-   repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: [--config=pyproject.toml]
