# Adapted from https://github.com/alan-turing-institute/scivision/blob/main/.github/workflows/publish-to-pypi.yml
name: Publish Tagged Python 🐍 distributions 📦 to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build-and-publish:
    name: Publish Tagged Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Build a binary wheel and a source tarball
      run: |
        poetry build
    - name: Publish tagged build to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
