# Adapted from https://github.com/alan-turing-institute/scivision/blob/main/.github/workflows/publish-to-pypi.yml
name: Publish all Python 🐍 distributions 📦 to Test PyPI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags-ignore:
      - v*

jobs:
  build-and-publish:
    name: Publish all Python 🐍 distributions 📦 to Test PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Create build version number for development builds
      if: ${{ ! startsWith(github.ref, 'refs/tags') }}
      run: |
        poetry version `poetry version -s``echo -alpha.`${{ github.run_number }}
    - name: Build a binary wheel and a source tarball
      run: |
        poetry build
    - name: Publish all builds to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
